//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approval_Srv
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoices
    {
        public int idinvoices { get; set; }
        public string name { get; set; }
        public string sourcepath { get; set; }
        public string destinationpath { get; set; }
        public Nullable<bool> iddanielapproval { get; set; }
        public Nullable<bool> idjeanapproval { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> approvaldate { get; set; }
        public bool moved { get; set; }
    }
}
