//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Approval_Srv
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int iduser { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> admin { get; set; }
    }
}
